In [1]:
import numpy as np
import pandas as pd

In [2]:
energy_data = pd.read_csv("energy_consumption.csv")

In [3]:
energy_data

   Energy_Source  Energy_Consumption(MWh)  Cost(Million$)
0     Geothermal                   2363.0           234.0
1        Biomass                   1241.0           147.0
2     Hydropower                      NaN           367.0
3        Biomass                   3041.0           392.0
4        Biomass                   3061.0           234.0
5           Wind                   2363.0             NaN
6     Hydropower                   3041.0           234.0
7     Hydropower                   3061.0           427.0
8     Hydropower                   3612.0           234.0
9        Biomass                   3612.0             NaN
10    Geothermal                   2390.0           427.0
11    Hydropower                   3041.0           315.0
12       Nuclear                   3612.0           132.0
13       Biomass                   3061.0           132.0
14          Wind                   2390.0           392.0
15    Geothermal                   3061.0           161.0
16       Nuclear                   2390.0           315.0
17       Nuclear                   3041.0           315.0
18          Wind                   2363.0           234.0
19    Geothermal                   3945.0           132.0
20       Biomass                   3139.0             NaN
21         Solar                   2363.0           300.0
22    Geothermal                   3824.0           300.0
23          Wind                   3061.0           427.0
24       Nuclear                   3824.0           132.0
25       Biomass                   2363.0           132.0
26    Geothermal                   2390.0           392.0
27         Solar                   3139.0           300.0
28         Solar                   3139.0           132.0
29    Hydropower                      NaN           392.0
30    Hydropower                   3139.0           234.0
31          Wind                   3945.0           367.0
32    Geothermal                   3139.0           127.0
33    Geothermal                   2363.0           315.0
34       Nuclear                      NaN           161.0
35       Nuclear                   2363.0           427.0
36       Nuclear                   2363.0           367.0
37    Hydropower                   2478.0           300.0
38    Geothermal                   1241.0           392.0
39    Geothermal                      NaN           315.0
40         Solar                   2363.0           132.0
41    Hydropower                   1241.0           161.0
42       Biomass                   1241.0           132.0
43    Hydropower                      NaN             NaN
44       Biomass                   2478.0             NaN
45         Solar                   3824.0           161.0
46          Wind                   2390.0           392.0
47    Geothermal                   3945.0           161.0
48         Solar                   2390.0           300.0
49    Geothermal                   3139.0           161.0

In [4]:
energy_data.isna().sum()  # Check for missing values

Energy_Source              0
Energy_Consumption(MWh)    5
Cost(Million$)             5
dtype: int64

In [5]:
energy_data["Energy_Consumption(MWh)"].fillna(energy_data["Energy_Consumption(MWh)"].mean())

0     2363.0
1     1241.0
2     2799.4
3     3041.0
4     3061.0
5     2363.0
6     3041.0
7     3061.0
8     3612.0
9     3612.0
10    2390.0
11    3041.0
12    3612.0
13    3061.0
14    2390.0
15    3061.0
16    2390.0
17    3041.0
18    2363.0
19    3945.0
20    3139.0
21    2363.0
22    3824.0
23    3061.0
24    3824.0
25    2363.0
26    2390.0
27    3139.0
28    3139.0
29    2799.4
30    3139.0
31    3945.0
32    3139.0
33    2363.0
34    2799.4
35    2363.0
36    2363.0
37    2478.0
38    1241.0
39    2799.4
40    2363.0
41    1241.0
42    1241.0
43    2799.4
44    2478.0
45    3824.0
46    2390.0
47    3945.0
48    2390.0
49    3139.0
Name: Energy_Consumption(MWh), dtype: float64

In [6]:
energy_data["Energy_Consumption(MWh)"].fillna(energy_data["Energy_Consumption(MWh)"].mean(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_15612\2837288390.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_data["Energy_Consumption(MWh)"].fillna(energy_data["Energy_Consumption(MWh)"].mean(), inplace=True)

In [7]:
energy_data.fillna(method="ffill")  # Forward fill missing values

C:\Users\HP\AppData\Local\Temp\ipykernel_15612\3879651691.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  energy_data.fillna(method="ffill")  # Forward fill missing values

   Energy_Source  Energy_Consumption(MWh)  Cost(Million$)
0     Geothermal                   2363.0           234.0
1        Biomass                   1241.0           147.0
2     Hydropower                   2799.4           367.0
3        Biomass                   3041.0           392.0
4        Biomass                   3061.0           234.0
5           Wind                   2363.0           234.0
6     Hydropower                   3041.0           234.0
7     Hydropower                   3061.0           427.0
8     Hydropower                   3612.0           234.0
9        Biomass                   3612.0           234.0
10    Geothermal                   2390.0           427.0
11    Hydropower                   3041.0           315.0
12       Nuclear                   3612.0           132.0
13       Biomass                   3061.0           132.0
14          Wind                   2390.0           392.0
15    Geothermal                   3061.0           161.0
16       Nuclear                   2390.0           315.0
17       Nuclear                   3041.0           315.0
18          Wind                   2363.0           234.0
19    Geothermal                   3945.0           132.0
20       Biomass                   3139.0           132.0
21         Solar                   2363.0           300.0
22    Geothermal                   3824.0           300.0
23          Wind                   3061.0           427.0
24       Nuclear                   3824.0           132.0
25       Biomass                   2363.0           132.0
26    Geothermal                   2390.0           392.0
27         Solar                   3139.0           300.0
28         Solar                   3139.0           132.0
29    Hydropower                   2799.4           392.0
30    Hydropower                   3139.0           234.0
31          Wind                   3945.0           367.0
32    Geothermal                   3139.0           127.0
33    Geothermal                   2363.0           315.0
34       Nuclear                   2799.4           161.0
35       Nuclear                   2363.0           427.0
36       Nuclear                   2363.0           367.0
37    Hydropower                   2478.0           300.0
38    Geothermal                   1241.0           392.0
39    Geothermal                   2799.4           315.0
40         Solar                   2363.0           132.0
41    Hydropower                   1241.0           161.0
42       Biomass                   1241.0           132.0
43    Hydropower                   2799.4           132.0
44       Biomass                   2478.0           132.0
45         Solar                   3824.0           161.0
46          Wind                   2390.0           392.0
47    Geothermal                   3945.0           161.0
48         Solar                   2390.0           300.0
49    Geothermal                   3139.0           161.0

In [8]:
energy_data.isna().sum()

Energy_Source              0
Energy_Consumption(MWh)    0
Cost(Million$)             5
dtype: int64

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
min_scaler = MinMaxScaler()
energy_data[["Energy_Consumption(MWh)", "Cost(Million$)"]] = min_scaler.fit_transform(
	energy_data[["Energy_Consumption(MWh)", "Cost(Million$)"]]
)

In [11]:
energy_data

   Energy_Source  Energy_Consumption(MWh)  Cost(Million$)
0     Geothermal                 0.414941        0.356667
1        Biomass                 0.000000        0.066667
2     Hydropower                 0.576331        0.800000
3        Biomass                 0.665680        0.883333
4        Biomass                 0.673077        0.356667
5           Wind                 0.414941             NaN
6     Hydropower                 0.665680        0.356667
7     Hydropower                 0.673077        1.000000
8     Hydropower                 0.876849        0.356667
9        Biomass                 0.876849             NaN
10    Geothermal                 0.424926        1.000000
11    Hydropower                 0.665680        0.626667
12       Nuclear                 0.876849        0.016667
13       Biomass                 0.673077        0.016667
14          Wind                 0.424926        0.883333
15    Geothermal                 0.673077        0.113333
16       Nuclear                 0.424926        0.626667
17       Nuclear                 0.665680        0.626667
18          Wind                 0.414941        0.356667
19    Geothermal                 1.000000        0.016667
20       Biomass                 0.701923             NaN
21         Solar                 0.414941        0.576667
22    Geothermal                 0.955251        0.576667
23          Wind                 0.673077        1.000000
24       Nuclear                 0.955251        0.016667
25       Biomass                 0.414941        0.016667
26    Geothermal                 0.424926        0.883333
27         Solar                 0.701923        0.576667
28         Solar                 0.701923        0.016667
29    Hydropower                 0.576331        0.883333
30    Hydropower                 0.701923        0.356667
31          Wind                 1.000000        0.800000
32    Geothermal                 0.701923        0.000000
33    Geothermal                 0.414941        0.626667
34       Nuclear                 0.576331        0.113333
35       Nuclear                 0.414941        1.000000
36       Nuclear                 0.414941        0.800000
37    Hydropower                 0.457470        0.576667
38    Geothermal                 0.000000        0.883333
39    Geothermal                 0.576331        0.626667
40         Solar                 0.414941        0.016667
41    Hydropower                 0.000000        0.113333
42       Biomass                 0.000000        0.016667
43    Hydropower                 0.576331             NaN
44       Biomass                 0.457470             NaN
45         Solar                 0.955251        0.113333
46          Wind                 0.424926        0.883333
47    Geothermal                 1.000000        0.113333
48         Solar                 0.424926        0.576667
49    Geothermal                 0.701923        0.113333

In [14]:
pd.get_dummies(energy_data, columns=["Energy_Source"]).fillna(0).astype("int")

,Energy_Consumption(MWh),Cost(Million$),Energy_Source_Biomass,Energy_Source_Geothermal,Energy_Source_Hydropower,Energy_Source_Nuclear,Energy_Source_Solar,Energy_Source_Wind
0,0,0,0,1,0,0,0,0
1,0,0,1,0,0,0,0,0
2,0,0,0,0,1,0,0,0
3,0,0,1,0,0,0,0,0
4,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,1
6,0,0,0,0,1,0,0,0
7,0,1,0,0,1,0,0,0
8,0,0,0,0,1,0,0,0
9,0,0,1,0,0,0,0,0
10,0,1,0,1,0,0,0,0
11,0,0,0,0,1,0,0,0
12,0,0,0,0,0,1,0,0
13,0,0,1,0,0,0,0,0
14,0,0,0,0,0,0,0,1
15,0,0,0,1,0,0,0,0
16,0,0,0,0,0,1,0,0
17,0,0,0,0,0,1,0,0
18,0,0,0,0,0,0,0,1
19,1,0,0,1,0,0,0,0
20,0,0,1,0,0,0,0,0
21,0,0,0,0,0,0,1,0
22,0,0,0,1,0,0,0,0
23,0,1,0,0,0,0,0,1
24,0,0,0,0,0,1,0,0
25,0,0,1,0,0,0,0,0
26,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,1,0
28,0,0,0,0,0,0,1,0
29,0,0,0,0,1,0,0,0
30,0,0,0,0,1,0,0,0
31,1,0,0,0,0,0,0,1
32,0,0,0,1,0,0,0,0
33,0,0,0,1,0,0,0,0
34,0,0,0,0,0,1,0,0
35,0,1,0,0,0,1,0,0
36,0,0,0,0,0,1,0,0
37,0,0,0,0,1,0,0,0
38,0,0,0,1,0,0,0,0
39,0,0,0,1,0,0,0,0
40,0,0,0,0,0,0,1,0
41,0,0,0,0,1,0,0,0
42,0,0,1,0,0,0,0,0
43,0,0,0,0,1,0,0,0
44,0,0,1,0,0,0,0,0
45,0,0,0,0,0,0,1,0
46,0,0,0,0,0,0,0,1
47,1,0,0,1,0,0,0,0
48,0,0,0,0,0,0,1,0
49,0,0,0,1,0,0,0,0